-- DEMODB.TEST_TABLE DEFINITION
CREATE TABLE `AUDIT`
(
    `IDX`     INT         NOT NULL AUTO_INCREMENT,
    `USER_ID` VARCHAR(50) NOT NULL,
    `DATE`    DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT AUDIT_PK PRIMARY KEY (IDX)
);

CREATE TABLE `USER`
(
    `USER_ID`       VARCHAR(50) NOT NULL,
    `USER_NAME`     VARCHAR(50) NOT NULL,
    `USER_PASSWORD` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_0900_AI_CI DEFAULT NULL,
    `USER_ROLE`     VARCHAR(50) NOT NULL                                         DEFAULT 'ROLE_USER',
    `ENABLE`        INT         NOT NULL                                         DEFAULT 1,
    CONSTRAINT USER_PK PRIMARY KEY (`USER_ID`)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8MB4
  COLLATE = UTF8MB4_0900_AI_CI;

CREATE TABLE `ROLE`
(
    `ROLE`      VARCHAR(50) NOT NULL,
    `ROLE_NAME` VARCHAR(50) NOT NULL,
    CONSTRAINT ROLE_PK PRIMARY KEY (ROLE)
);

INSERT INTO `ROLE` (ROLE, ROLE_NAME)
VALUES ('ROLE_ADMIN', 'ADMIN');